### ISSUE TITLE
Use `.safeParse()` instead of `.parse()`

### ISSUE THREAD

**Issue by jonahsnider** [vercel-labs/next-swr-endpoints#6]
https://github.com/vercel-labs/next-swr-endpoints/blob/9c93696201d50f1034544115d47c0ea0291f945b/packages/next-swr-endpoints/src/swr-server-endpoint-loader.ts#L49

[`.safeParse()`](https://www.npmjs.com/package/zod#safeparse) will return a result object instead of throwing an error.

**Comment by Schniz** [comment]
I think throwing is better here as it’s simplifying the API (this package has no dependency on zod, you can write your own parser) but we need to return an HTTP 400 if the values don’t match
